### ISSUE TITLE
Place a buy order

### ISSUE THREAD

**Issue by jvandenaardweg** [jvandenaardweg/coinaly#4]
Progress screenshot below.

Limit market order is working in branche: https://github.com/jvandenaardweg/coinaly/tree/feature/buy-order, needs a few more tweaks to finalize

If you use that branche now: use it at your own risk.

**Features:**
- Shows when your price is above or below the current market price (live updates)
- Use `last`, `24hr high`, `24hr low` market data to set price
- Use amount percentages to generate the proper amount with the given price
- Ability to round the amount (`Math.floor()`)
- Show fiat prices in USD. So you get a better feeling how much your order is
- It's really fast to place an order. Just 3 clicks away. You can place one within 5 seconds from any page. So you can react fast on market changes.
- You can place an order by just tapping, no need to manually adjust numbers with a keyboard

**TODO:**
- [ ] Make [ + ] [ - ] buttons work at price
- [ ] Give a warning when you have insufficient funds before placing an order
- [ ] Show availability of BTC/ETH/USDT at better place on screen
- [ ] Deduct fee from total amount calculation
- [ ] Use checkmarks at market search page for currently selected market (instead of round radio)
- [ ] Show [Advanced] button to toggle advanced market order options (conditional, order types etc...)

When you have not selected a market, you will be given the option to search for one
![screenshot 2018-01-16 09 41 38](https://user-images.githubusercontent.com/5155373/34979402-78cc51d4-faa1-11e7-82fa-0024d274defd.png)

Setting the price and amount
![screenshot 2018-01-16 09 30 37](https://user-images.githubusercontent.com/5155373/34978958-3c2a821a-faa0-11e7-8917-ba768abb838e.png)

**Comment by jvandenaardweg** [comment]
Progress screenshot below.

Limit market order is working, needs a few more tweaks to finalize

![Uploading Screenshot 2018-01-16 09.30.37.png…]()

**Comment by jvandenaardweg** [comment]
Progress moved to PR https://github.com/jvandenaardweg/coinaly/issues/4
